export const listOfInterests = [
  { id: 1, interest: "Programar 🖥️" },
  { id: 2, interest: "Cine 🎬" },
  { id: 3, interest: "Fotografía 📸" },
  { id: 4, interest: "Videojuegos 🎮" },
  { id: 5, interest: "Leer 📚" },
  { id: 6, interest: "Viajar ✈️" },
  { id: 7, interest: "Cocinar 🍳" },
  { id: 8, interest: "Música 🎵" },
  { id: 9, interest: "Escalada 🧗" },
  { id: 10, interest: "Pintura 🎨" },
  { id: 11, interest: "Escribir ✍️" },
  { id: 12, interest: "Jardinería 🌿" },
  { id: 13, interest: "Buceo 🤿" },
  { id: 14, interest: "Yoga 🧘" },
  { id: 15, interest: "Meditación 🕉️" },
  { id: 16, interest: "Teatro 🎭" },
  { id: 17, interest: "Danza 💃" },
  { id: 18, interest: "Bicicleta 🚲" },
  { id: 19, interest: "Senderismo 🥾" },
  { id: 20, interest: "Natación 🏊" },
  { id: 21, interest: "Tecnología 💻" },
  { id: 22, interest: "Animales 🐾" },
  { id: 23, interest: "Voluntariado 👫" },
  { id: 24, interest: "Arqueología 🔍" },
  { id: 25, interest: "Astronomía 🌌" },
  { id: 26, interest: "Filosofía 📖" },
  { id: 27, interest: "Modelismo 🚂" },
  { id: 28, interest: "Fotografía aérea con drones 🚁" },
  { id: 29, interest: "Carpintería 🪑" },
  { id: 30, interest: "Costura 🪡" },
];
